package com.example.mynewcompose.presentation.components.list

import com.example.mynewcompose.ui.theme.blueKlein
import com.example.mynewcompose.ui.theme.blueSky
import com.example.mynewcompose.ui.theme.greenEmerald
import com.example.mynewcompose.ui.theme.greySlate
import com.example.mynewcompose.ui.theme.mintSoft
import com.example.mynewcompose.ui.theme.orangeDown
import com.example.mynewcompose.ui.theme.orangePeach
import com.example.mynewcompose.ui.theme.pinkPale
import com.example.mynewcompose.ui.theme.purpleDeep
import com.example.mynewcompose.ui.theme.purpleLavender
import com.example.mynewcompose.ui.theme.redCoral
import com.example.mynewcompose.ui.theme.yellowVanilla

val friendList: List<String> =
    listOf(
        "Sofía",
        "Mateo",
        "Valentina",
        "Santiago",
        "Isabella",
        "Sebastián",
        "Camila",
        "Matías",
        "Valeria",
        "Alejandro",
        "Lucía",
        "Daniel",
        "Mariana",
        "Diego",
        "Gabriela",
        "Leonardo",
        "Emma",
        "Adrián",
        "Regina",
        "Samuel",
        "Olivia",
        "David",
        "Elena",
        "Javier",
        "Zoe",
        "Iker",
        "Mía",
        "Emiliano",
        "Renata",
        "Joaquín",
        "Liam",
        "Ava",
        "Noah",
        "Charlotte",
        "Oliver",
        "Amelia",
        "Elijah",
        "Harper",
        "William",
        "Evelyn",
        "James",
        "Abigail",
        "Benjamin",
        "Emily",
        "Lucas",
        "Elizabeth",
        "Henry",
        "Aria",
        "Alexander",
        "Chloe",
        "Michael",
        "Victoria",
        "Daniel",
        "Grace",
        "Pablo",
        "Paula",
        "Hugo",
        "Carla",
        "Martín",
        "Alba",
        "Jorge",
        "Julia",
        "Manuel",
        "Noa",
        "Francisco",
        "Sara",
        "Carlos",
        "Carmen",
        "Ángel",
        "Laura",
        "Miguel",
        "Marta",
        "Rafael",
        "Andrea",
        "José",
        "Ana",
        "Fernando",
        "María",
        "Luis",
        "Cristina",
        "Sergio",
        "Patricia",
        "Ricardo",
        "Verónica",
        "Felipe",
        "Clara",
        "Andrés",
        "Beatriz",
        "Juan",
        "Raquel",
        "Óscar",
        "Silvia",
        "Eduardo",
        "Lorena",
        "Esteban",
        "Natalia",
    )

val colorsList =
    listOf(
        yellowVanilla,
        orangePeach,
        pinkPale,
        mintSoft,
        blueSky,
        purpleLavender,
        blueKlein,
        purpleDeep,
        greySlate,
        greenEmerald,
        orangeDown,
        redCoral,
    )
